class Tensor:
    def __init__(self, data: list[float] | list[list[float]]) -> None: ...
    
    def get(self, index: int) -> float: ...
    def size(self) -> int: ...
    def shape(self) -> list[int]: ...
    def ndim(self) -> int: ...

    def sum(self) -> float: ...
    def mean(self) -> float: ...
    def max(self) -> float: ...
    def min(self) -> float: ...

    def __add__(self, other: Tensor | float) -> Tensor: ...
    def __sub__(self, other: Tensor | float) -> Tensor: ...
    def __mul__(self, other: Tensor | float) -> Tensor: ...
    def __truediv__(self, other: Tensor | float) -> Tensor: ...

    def reshape(self, new_shape: list[int]) -> Tensor: ...
    def flatten(self) -> Tensor: ...
    def transpose(self) -> Tensor: ...

def zeros(shape: list[int]) -> Tensor: ...
def ones(shape: list[int]) -> Tensor: ...    