class Tensor:
    def __init__(self, data: list[float] | list[list[float]]) -> None: ...
    
    def get(self, index: int) -> float: ...
    def size(self) -> int: ...
    def shape(self) -> list[int]: ...
    def ndim(self) -> int: ...

    def sum(self) -> float: ...
    def mean(self) -> float: ...
    def max(self) -> float: ...
    def min(self) -> float: ...
    def argmax(self) -> int: ...
    def argmin(self) -> int: ...
    def abs(self) -> Tensor: ...
    def clip(self, min: float, max: float) -> Tensor: ...
    def pow(self, n: int) -> Tensor: ...
    def sqrt(self) -> Tensor: ...
    def stddev(self) -> float: ...
    def var(self) -> float: ...
    def normalize(self) -> Tensor: ...
    def log(self) -> Tensor: ...

    def __add__(self, other: Tensor | float) -> Tensor: ...
    def __sub__(self, other: Tensor | float) -> Tensor: ...
    def __mul__(self, other: Tensor | float) -> Tensor: ...
    def __truediv__(self, other: Tensor | float) -> Tensor: ...
    def __repr__(self) -> str: ...

    def reshape(self, new_shape: list[int]) -> Tensor: ...
    def flatten(self) -> Tensor: ...
    def transpose(self) -> Tensor: ...
    def dot(self, other: Tensor) -> Tensor: ...
    def matmul(self, other: Tensor) -> Tensor: ...

    def __radd__(self, other: float) -> Tensor: ...
    def __rsub__(self, other: float) -> Tensor: ...
    def __rmul__(self, other: float) -> Tensor: ...
    def __rtruediv__(self, other: float) -> Tensor: ...

def zeros(shape: list[int]) -> Tensor: ...
def ones(shape: list[int]) -> Tensor: ...    